#!/usr/bin/bash
#  | |     _   ,_  | |   , _|_ | |        | |_|_          _  _  _   
#  |/ \   |/  /  | |/ \_/ \_|  |/  |   |  |/  |  |  |  |_/ |/ |/ |  
#  |   |_/|__/   |_/\_/  \/ |_/|__/ \_/|_/|__/|_/ \/ \/    |  |  |_/
#                                         |\                        
#                                         |/


herbstclient emit_hook reload


# -- const
mypath=`realpath $0`
mydir=`dirname $mypath`
gap=8


# -- chain
cmds=""
hc() {
  cmds="$cmds , $@"
}


# -- keep it quiet
hc lock
hc keyunbind --all


# -- wm settings
hc set wmname LG3D
hc set always_show_frame 0
hc set smart_frame_surroundings 0
hc set frame_bg_transparent 0
hc set default_frame_layout 2
hc set snap_gap $gap
hc set focus_follows_mouse 0
# -- /settings

# -- monitors
hc detect_monitors
# -- /monitors

# -- theme
hc set frame_gap $gap
hc set frame_padding 0
hc set frame_border_width 0
hc set frame_border_active_color "#191919"
hc set frame_border_normal_color "#000000"
hc set frame_bg_active_color "#121317"
hc set frame_bg_normal_color "#121317"
hc set frame_active_opacity 80
hc set frame_normal_opacity 50

hc set window_gap 0
hc set window_border_width 4
hc set window_border_inner_width 0
hc set window_border_active_color "#202020"
hc set window_border_normal_color "#151515"
hc set window_border_inner_color "#e0e0e0"
hc set window_border_urgent_color "#802828"
# -- /theme

# -- controls
hc keybind Super+Shift+Escape quit        
hc keybind Super+q close_or_remove        
hc keybind Super+b split h 0.5            
hc keybind Super+v split v 0.5            
hc keybind Super+i cycle                  
hc keybind Super+u cycle -1               
hc keybind Super+Left cycle               
hc keybind Super+Right cycle -1           
hc keybind Super+space cycle_layout +1    
hc keybind Super+f floating               
hc keybind Super+g fullscreen toggle      
hc keybind Super+y use_index -1           
hc keybind Super+o use_index +1           
hc keybind Super+Down use_index -1        
hc keybind Super+Up use_index +1          
hc keybind Super+Shift+y move_index -1    
hc keybind Super+Shift+o move_index +1    
hc keybind Super+r chain - lock - rotate - rotate - unlock
hc keybind Super+Escape reload            
hc keybind Super+Return spawn sh-dmenufav           
hc keybind Super+9 emit_hook vol_down
hc keybind Super+0 emit_hook vol_up
hc keybind Super+8 emit_hook vol_mute

dir=("left" "right" "up" "down")
key=("h" "l" "k" "j")
for i in 0 1 2 3; do
  hc keybind Super+${key[$i]} focus ${dir[$i]}
  hc keybind Super+Shift+${key[$i]} shift ${dir[$i]}
  hc keybind Super+Mod1+${key[$i]} resize ${dir[$i]} +0.05
done
# -- /controls

# -- tags
hc rename default 1
hc keybind Super+1 use 1
hc keybind Super+Shift+1 move 1
for i in `seq 2 4`; do
  hc add $i
  hc keybind Super+$i use $i
  hc keybind Super+Shift+$i move $i
done
# -- /tags

# -- mouse
hc mouseunbind
hc mousebind Super+B1 move
hc mousebind Super+B3 resize
hc mousebind Super+B2 zoom
# -- /mouse

# -- rules
hc unrule --all
hc rule title=stalonetray manage=off
hc rule title=playontv tag=4 fullscreen=on
hc rule class=Conky manage=off
hc rule class~".*nboard" manage=off
hc rule class~.* focus=on
hc rule windowtype=_NET_WM_WINDOW_TYPE_DIALOG focus=on pseudotile=on
# -- /rules

# -- ACTIVATE
hc set_layout max
hc unlock
herbstclient chain $cmds &
# -- /ACTIVATE

unset -f hc
