#!/usr/bin/bash
#  | |     _   ,_  | |   , _|_ | |        | |_|_          _  _  _   
#  |/ \   |/  /  | |/ \_/ \_|  |/  |   |  |/  |  |  |  |_/ |/ |/ |  
#  |   |_/|__/   |_/\_/  \/ |_/|__/ \_/|_/|__/|_/ \/ \/    |  |  |_/
#                                         |\                        
#                                         |/


herbstclient emit_hook reload


# -- const
mypath=`realpath $0`
mydir=`dirname $mypath`
gap=8
bar_height=16


# -- chain
cmds=""
hc() {
  cmds="$cmds , $@"
}


# -- keep it quiet
hc lock
hc keyunbind --all


# -- wm settings
hc set wmname LG3D
hc set always_show_frame 0
hc set smart_frame_surroundings 0
hc set frame_bg_transparent 0
hc set default_frame_layout 2
hc set snap_gap $gap
hc set focus_follows_mouse 0


# -- monitors
hc detect_monitors
hc pad 0 $bar_height


# -- theme
hc set frame_gap $gap
hc set frame_padding 0
hc set frame_border_width 0
hc set frame_border_active_color "#191919"
hc set frame_border_normal_color "#000000"
hc set frame_bg_active_color "#101010"
hc set frame_bg_normal_color "#101010"
hc set frame_active_opacity 20
hc set frame_normal_opacity 5

hc set window_gap 0
hc set window_border_width 3
hc set window_border_inner_width 1
hc set window_border_active_color "#e0e0e0"
hc set window_border_normal_color "#101010"
hc set window_border_inner_color "#101010"
hc set window_border_urgent_color "#ac4142"


# -- tags
hc rename default 1
hc add 2
hc add 3
hc add 4


# -- mouse
hc mouseunbind
hc mousebind Super+B1 move
hc mousebind Super+B3 resize
hc mousebind Super+B2 zoom


# -- rules
hc unrule --all
hc rule class="Tint2" manage=off
hc rule class~".*nboard" manage=off
hc rule class~.* focus=on
hc rule windowtype=_NET_WM_WINDOW_TYPE_DIALOG focus=on pseudotile=on
hc rule windowrole=LAUNCHER focus=on pseudotile=on


# -- ACTIVATE
hc set_layout max
hc unlock
herbstclient chain $cmds &

unset -f hc


# -- panel
killall tint2
#tint2 &

scrw=`xrandr | grep '*' | cut -dx -f1`
bar_cmd=(\
  "bar"
  "-d" 
  "-g $(( $scrw - 2*$gap ))x${bar_height}+$gap+0"
  "-f -benis-lemon-medium-r-normal--10-110-75-75-m-50-iso8859-1" 
  "-B #00000000"
  "-F #FFe0e0e0"
  )

herbstclient -w reload &
bar_pid=$!
(while ps -p $bar_pid >/dev/null 2>&1; do
   $mydir/bar
   sleep 0.3
 done) | ${bar_cmd[@]}
