#!/usr/bin/sh
#  | |     _   ,_  | |   , _|_ | |        | |_|_          _  _  _   
#  |/ \   |/  /  | |/ \_/ \_|  |/  |   |  |/  |  |  |  |_/ |/ |/ |  
#  |   |_/|__/   |_/\_/  \/ |_/|__/ \_/|_/|__/|_/ \/ \/    |  |  |_/
#                                         |\                        
#                                         |/


herbstclient emit_hook reload


# -- const
mypath=`realpath $0`
mydir=`dirname $mypath`
scrw=`xrandr | grep '*' | cut -dx -f1`
[[ $scrw -gt 1024 ]] && gap=8 || gap=0
bar_height=25


# -- chain
cmds=""
hc() {
  cmds="$cmds , $@"
}


# -- keep it quiet
hc lock
hc keyunbind --all


# -- wm settings
hc set wmname LG3D
hc set always_show_frame 0
hc set smart_frame_surroundings 0
hc set frame_bg_transparent 0
hc set default_frame_layout 2
hc set snap_gap $gap
hc set focus_follows_mouse 0
hc set focus_crosses_monitor_boundaries 0


# -- monitors
hc detect_monitors
hc pad 0 $(( $bar_height )) 0 0 0


# -- theme
hc set frame_gap $gap
hc set frame_padding 0
hc set frame_border_width 0
hc set frame_border_active_color "#191919"
hc set frame_border_normal_color "#000000"
hc set frame_bg_active_color "#90a959"
hc set frame_bg_normal_color "#151515"
hc set frame_active_opacity 100
hc set frame_normal_opacity 100

hc set window_gap 0
hc set window_border_width 3
hc set window_border_inner_width 1
hc set window_border_active_color "#d0d0d0"
hc set window_border_normal_color "#303030"
hc set window_border_inner_color "#101010"
hc set window_border_urgent_color "#ac4142"


# -- tags
hc rename default 1
hc add 2
hc add 3
hc add 4


# -- mouse
hc mouseunbind
hc mousebind Super+B1 move
hc mousebind Super+B3 resize
hc mousebind Super+B2 zoom


# -- rules
hc unrule --all
hc rule class~.* focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK)' manage=off
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' focus=on pseudotile=on 
hc rule windowrole='LAUNCHER' focus=on pseudotile=on


# -- ACTIVATE
hc set_layout max
hc unlock
herbstclient chain $cmds &

unset -f hc


# -- compositing
#[[ -z `pidof xcompmgr` ]] && xcompmgr -c -C -t-5 -l-5 -r3.8 -o.50 &


# -- panel
conky_tmp="/tmp/hlwm_conky.rc"
sed "s/%scrw%/$scrw/g" $XDG_CONFIG_HOME/conky/graphical > ${conky_tmp} 
killall conky
conky -c ${conky_tmp} &


# -- floatmon
. $mydir/floatmon
