#!/usr/bin/env bash

hc() { herbstclient "$@" ;}

action="$1"
search="${@:2}"

# match all titles to window IDs
id_titles() {
  hc attr clients. | while read line
  do
    id=`echo $line | awk '/0x/ {print $1}'`
    [[ -z "$id" ]] && continue
    title=`hc get_attr clients.${id}.title`

    echo $id ${title,,}
  done
}

match() {
  grep "${search,,}" | awk '{print $1}'
}

jump() {
  read id
  if [[ -n $id ]]; then
    [[ "$action" == "j" ]] && hc jumpto $id
    [[ "$action" == "b" ]] && hc bring $id
  fi
}

id_titles | match | jump
