#!/usr/bin/env bash

tags="`herbstclient tag_status`"

echo $tags | awk \
  '/#fl/ {print("${color4}FLOATMON");exit}
   {
     gsub(/\#[0-9]/, "${color4}•");
     gsub(/\![0-9]/, "${color1}•");
     gsub(/\:[0-9]/, "${color7}•");
     gsub(/\.[0-9]/, "${color}•");
     gsub(/-[0-9a-z]+/, "");
     print
   }
  '
