#!/bin/bash

## FUNCTIONS
# Pastebin
pb() {
  curl -sF "c=@${1:--}" -w "%{redirect_url}" https://ptpb.pw -o /dev/stderr | xclip -i -selection CLIPBOARD
}

astart() {
  [[ -z `pidof $1` ]] && $@
}

cstart() {
  while [[ -z `pidof $1` ]]; do
    sleep .5
  done
  astart ${@:2}
}

man() {
    env LESS_TERMCAP_mb=$'\E[01;31m' \
    LESS_TERMCAP_md=$'\E[01;38;5;74m' \
    LESS_TERMCAP_me=$'\E[0m' \
    LESS_TERMCAP_se=$'\E[0m' \
    LESS_TERMCAP_so=$'\E[38;5;246m' \
    LESS_TERMCAP_ue=$'\E[0m' \
    LESS_TERMCAP_us=$'\E[04;38;5;146m' \
    man "$@"
}

lns() {
  ln -s `realpath $1` $2
}

mpvp() {
  if [[ $1 == "tv" ]]; then
    url="${2:-`xclip -o -selection clipboard`}"
    herbstclient reload
    args="--no-cache --ao=alsa:device=hdmi --title=playontv $url"
  else
    args="${1:-`xclip -o -selection clipboard`}"
  fi
  mpv $args
} 

calc() {
  python -c "from math import *; print($@)"
}


## ALIASES

# Shell commands
alias ls='ls --group-directories-first --color=always --classify -h'
alias less='less -RS'
alias cp='cp -i'
alias mv='mv -i'
alias rm='rm -rfI'
alias df='df -h'
alias du='du -h'
alias dud='du -hcs * | sort -hr'
alias la='ls -lA'
alias grep='grep --color=auto'
alias dmesg='dmesg --color'
alias ocd='cd -'

# Shorten stuff
alias s='ssh'
alias v='vim'
alias l='ls'
alias o='xdg-open'
alias t='tmux -f $XDG_CONFIG_HOME/tmux/local.conf'
alias g='grep --color=auto -Rni'
alias q='exit'

# Actions
alias po="sudo poweroff"
alias re="sudo reboot"

# Utils
alias redot='source $HOME/.bashrc'
alias rexrdb='xrdb -merge $XDG_CONFIG_HOME/xorg/xresources'
alias lastj="sudo journalctl -b-1"
alias valgr='valgrind --db-attach=yes --leak-check=yes --tool=memcheck --num-callers=16 --leak-resolution=high --track-origins=yes'

# Force stuff to obey XDG
alias rtorrent="rtorrent -n -o import=${XDG_CONFIG_HOME}/rtorrent/config.rc"
alias weechat="weechat -d $XDG_CONFIG_HOME/weechat"
alias skype="skype --dbpath=$XDG_CONFIG_HOME/skype"
alias easystroke="easystroke -c $XDG_CONFIG_HOME/easystroke"
alias mypaint="mypaint -c $XDG_CONFIG_HOME/mypaint"

# Clipboard
alias Cpr="xclip -o -selection PRIMARY"
alias Cse="xclip -o -selection SECONDARY"
alias Ccl="xclip -o -selection CLIPBOARD"
alias Cc="xclip -i -selection PRIMARY"

