#!/bin/bash

cat <<EOF
   _                                        
  | |                                       
  | |   __   __ _|_  , _|_  ,_    __,    _  
  |/ \_/  \_/  \_|  / \_|  /  |  /  |  |/ \_
   \_/ \__/ \__/ |_/ \/ |_/   |_/\_/|_/|__/ 
                                      /|    
  Doing the work so I don't have to™  \|    

EOF
  

# Assume we've just curl'd this file from:
# https://github.com/vixus0/dotfiles/raw/master/bootstrap

# Stop on any error
set -e

host="$(hostname -s)"

echo "About to start bootstrap on ${host}."
echo "Press enter if that's really what you want to do."
read


# Update pacman
su -c pacman -Syu


# Check we have sudo
if test -z $(which sudo); then
  echo "Need to install and set up sudo first."
  su -c pacman -S sudo
  echo "Press enter to start visudo. Add the following:"
  echo "$(whoami) ALL=(ALL) /usr/bin/pacman"
  echo "$(whoami) ALL=(ALL) NOPASSWD: /usr/bin/poweroff, /usr/bin/reboot, /usr/bin/setkeycodes"
  read
  su -c visudo
  echo "Great, assuming sudo is properly set up for pacman."
fi


# Get git to clone dotfile repo
if test -z $(which git); then
  echo "Installing git"
  sudo pacman -S git
fi

if test ! -d "$HOME/dots"; then
  echo "Cloning dotfiles from github"
  git clone https://github.com/vixus0/dotfiles dots
fi


# Enter dotfiles dir
cd $HOME/dots


# Base setup
echo "Installing base packages from pac.base"
sudo pacman -S --needed $(< pac.base)


# Install configs for base packages
echo "Stowing base config files"
rm $HOME/.bash{_profile,rc}
stow -S base 


# Install packages and configs for host
echo "Installing packages from pac.$host"
test -f pac.$host && sudo pacman -S --needed $(< pac.$host)
echo "Stowing $host config files"
test -d $host && stow -S $host


# Install desktop packages
echo "Install desktop packages?"
read choice

if test "$choice" = "y"; then
  echo "Installing packages from pac.desktop"
  sudo pacman -S --needed $(< pac.desktop)
  echo "Stowing desktop config files"
  stow -S desktop
fi


# Finish up
echo "All done. Probably should reboot or logout/in."
echo "AUR packages can be downloaded using:"
echo "aur dl <pac.aur"
