#!/bin/bash
#   _                                        
#  | |                                       
#  | |   __   __ _|_  , _|_  ,_    __,    _  
#  |/ \_/  \_/  \_|  / \_|  /  |  /  |  |/ \_
#   \_/ \__/ \__/ |_/ \/ |_/   |_/\_/|_/|__/ 
#                                      /|    
#  Doing the work so I don't have to.  \|    
#  


# Headless packages
cpackages=(\
  "bash-completion"
  "openssh"
  "stow"
  "vim"
  "tmux"
  "weechat"
  )

# GUI packages
# AUR packages must be at the end?
xpackages=(\
  "xorg-server"
  "xorg-xrdb"
  "xorg-setxkbmap"
  "xorg-xset"
  "xorg-xmodmap"
  "hsetroot"
  "herbstluftwm"
  "xcompmgr"
  "tint2"
  "firefox"
  "adobe-source-code-pro-fonts"
  "sxiv"
  "termite-git"
  "sxhkd"
  )


# Check we have sudo
if [[ -z `which sudo` ]]; then
  echo "Install sudo first!"
  exit
fi


# Perform an update
sudo pacman -Syu


# Base setup
if [[ -z `pacman -Q git` ]]; then
  sudo pacman -S git
fi


# Pull my dotfiles repository
if [[ ! -d "$HOME/dots" ]]; then
  git clone https://github.com/vixus0/dotfiles.git dots
fi
cd "$HOME/dots"


# Install package-query and yaourt
if [[ -z `pacman -Q yaourt` ]]; then
  pushd
  
  cd abs/package-query
  makepkg --syncdeps --clean
  sudo makepkg --install

  cd ../yaourt
  makepkg --syncdeps --clean
  sudo makepkg --install

  popd
fi


# Install the essential packages
yaourt -S --needed "${cpackages[@]}"


# Install GUI packages
[[ $1 == "gui" ]] && yaourt -S --needed "${xpackages[@]}"


# Install configs for aforementioned packages
cd $HOME
mkdir -p .config .local/{bin,include,lib,share/applications} .cache .ssh
cd dots

allpackages="${cpackages[@]} ${xpackages[@]}"

for p in $allpackages; do
  echo "Searching config for $p..."
  [[ -z `pacman -Q $p` ]] && continue
  cfgd=`find . -maxdepth 1 -name "cfg.$p" -type d`
  if [[ -n "$cfgd" ]]; then
    echo "Installing config for $p..."
    cfgd=${cfgd/\//}
    cfgd=${cfgd##.}
    stow -S "$cfgd" 
  fi
done

