"         o             
"   _  _  _   
"   |  |_|  / |/ |/ |  
"    \/  |_/  |  |  |_/
"  


set nocompatible

set directory=$XDG_CACHE_HOME/vim,~/,/tmp
set backupdir=$XDG_CACHE_HOME/vim,~/,/tmp
set viminfo+=n~/.cache/vim/viminfo
set runtimepath=$XDG_CONFIG_HOME/vim,$VIM,$VIMRUNTIME
set path=.,,**
let $MYVIMRC="$XDG_CONFIG_HOME/vim/vimrc"

if empty(glob("$XDG_CONFIG_HOME/vim/autoload/plug.vim"))
  execute "!curl -fLo $XDG_CONFIG_HOME/vim/autoload/plug.vim --create-dirs https://raw.github.com/junegunn/vim-plug/master/plug.vim"
endif

call plug#begin("$XDG_DATA_HOME/vim/plugins")
Plug 'morhetz/gruvbox'
Plug 'tpope/vim-surround'
Plug 'Valloric/YouCompleteMe'
Plug 'sjl/gundo.vim'
Plug 'Shutnik/jshint2.vim'
Plug 'jiangmiao/auto-pairs'
call plug#end()

let g:tex_flavor='latex'
let g:ycm_autoclose_preview_window_after_completion = 1
let g:ycm_global_ycm_extra_conf = "~/.config/vim/.ycm_extra_conf.py"

source $XDG_CONFIG_HOME/vim/functions.vim
source $XDG_CONFIG_HOME/vim/binds.vim

autocmd InsertEnter * :set norelativenumber | :set number
autocmd InsertLeave * :set nonumber | :set relativenumber

au BufNewFile,BufRead *.tex,*.md call WrapOn()
au BufNewFile,BufRead *.src set filetype=fortran
au BufNewFile,BufRead *.fcm set filetype=fortran
au BufNewFile,BufRead *.frag,*.vert,*.fp,*.vp,*.glsl set filetype=glsl

filetype plugin indent on
set incsearch
set hlsearch
set scrolloff=2
set ignorecase
set smartcase
set expandtab
set tabstop=2
set shiftwidth=2
set laststatus=2
set nowrap
set relativenumber
set modeline
set cursorline
set clipboard+=unnamed
set backspace+=start,eol,indent
set omnifunc=syntaxcomplete#Complete
set wildmode=longest,list,full
set wildmenu
set showcmd
set timeoutlen=1000
set ttimeoutlen=0

set foldmethod=indent   "fold based on indent
set foldnestmax=10      "deepest fold is 10 levels
set nofoldenable        "dont fold by default
set foldlevel=1         "this is just what i use

if has('gui_running')
  set guioptions="aegitc"
  set guifont=M+\ 2m\ medium\ 14
  :inoremap <M-l> <Esc>l
  :inoremap <M-j> <Esc>j
  :inoremap <M-k> <Esc>k
  :inoremap <M-h> <Esc>h
endif

syntax on
set background=dark
colorscheme gruvbox
let g:gruvbox_contrast_dark = 'hard'
let &colorcolumn=join(range(81,999),",")
