#!/bin/bash

pad=0
bar=40

bspc config focused_border_color "#282828"
bspc config normal_border_color  "#282828"
bspc config normal_border_color  "#282828"
bspc config presel_border_color  "#83a598"

bspc config border_width        2
bspc config window_gap          8
bspc config top_padding         $pad
bspc config bottom_padding      $pad
bspc config left_padding        $bar
bspc config right_padding       $pad

bspc config split_ratio         0.52
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true
bspc config focus_follows_pointer true

bspc monitor -d 1 2 3 4

# autostart
if test ! -f /tmp/bspwm_started
then
  hsetroot -fill ~/.wallpaper.png &
  xss-lock blurlock &
  tint2 &
  sxhkd &
  dunst &
  compton -b &
  redshift -l 56.1107:3.1674 -t 6500:4800 &
  volumeicon &
  wicd-gtk --tray &
  xsetroot -cursor_name left_ptr &
  touch /tmp/bspwm_started
fi
