#!/bin/bash

restart () {
  (pkill --full "$1"; "$@" &)
}

# autostart
wal -R &
xsetroot -cursor_name left_ptr &

restart xss-lock -- i3lock-extra -m pixelize $HOME/img/lock-icon.png
restart tint2
restart sxhkd
restart dunst
restart compton -b
restart redshift -l 56.1107:3.1674 -t 6500:4800
restart volumeicon
restart connman-ui-gtk
restart cbatticon
restart $HOME/git/lightsOn/lightsOn.sh

# config bspwm
bspc config focused_border_color "#000000"
bspc config normal_border_color  "#000000"

bspc config border_width        4
bspc config window_gap          12

bspc config split_ratio         0.5
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_follows_pointer false

bspc monitor -d 1 2 3 4

