## Set up Xorg
#

XORG_DIR="$XDG_CONFIG_HOME/xorg"

# Execute global scripts
if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/*; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

# Set correct keymap and specify compose key
setxkbmap gb && setxkbmap -option compose:ralt

# Process PCF fonts
xset +fp ~/.fonts/PCF && xset fp rehash &

# Merge Xresources
xrdb -merge $XORG_DIR/xresources &

# Xmodmap
xmodmap $XORG_DIR/xmodmap &

# Host specific stuff
if [ -d $XORG_DIR/xinitrc.d ]; then
  for f in $XORG_DIR/xinitrc.d/`hostname`*; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

## Start Programs
#

# set wallpaper
[[ -e ~/.wall ]] && . ~/.wall

# redshift for night viewing (kdy)
redshift -l 56.1107:3.1674 -t 6500:4800 &

# rxvt-unicode daemon
urxvtd -q -f -o &

# composite manager
xcompmgr -c -C -t-5 -l-5 -r3.8 -o.50 &

# hotkey daemon
sxhkd &

# Window Manager
exec herbstluftwm
