#!/usr/bin/bash

hc() {
  cmds="$cmds , $@"
}

# Settings
hc set always_show_frame 0
hc set smart_frame_surroundings 0
hc set frame_bg_transparent 1
hc set default_frame_layout 2
hc set snap_gap 2
hc set focus_follows_mouse 1

# Set up monitors
hc detect_monitors
hc pad 0 16

# Theme
hc set frame_gap 4
hc set frame_padding 0
hc set frame_border_width 0
hc set frame_border_active_color "#191919"
hc set frame_border_normal_color "#000000"
hc set frame_bg_active_color "#191919"
hc set frame_bg_normal_color "#000000"
hc set frame_active_opacity 80
hc set frame_normal_opacity 20

hc set window_gap 0
hc set window_border_width 2
hc set window_border_inner_width 0
hc set window_border_active_color "#202020"
hc set window_border_normal_color "#191919"
hc set window_border_inner_color "#e0e0e0"
hc set window_border_urgent_color "#802828"

# Keybinds
hc keyunbind --all
hc keybind Super+Shift+Escape quit        #i ▩ # Quit
hc keybind Super+q close_or_remove        #i × # Close window
hc keybind Super+b split h 0.5            #i │ # Horizontal split
hc keybind Super+v split v 0.5            #i ─ # Vertical split
hc keybind Super+i cycle                  #i ❯ # Cycle forward in frame
hc keybind Super+u cycle -1               #i ❮ #       backward
hc keybind Super+space cycle_layout +1    #i ⮥ # Change layout type
hc keybind Super+f floating               #i ⮛ # Switch to floating mode
hc keybind Super+g fullscreen toggle      #i ⮩ # Make window fullscreen
hc keybind Super+y use_index -1           #i ◁ # Prev tag
hc keybind Super+o use_index +1           #i ▷ # Next 
hc keybind Super+Shift+y move_index -1    #i ◀ # Move to prev tag
hc keybind Super+Shift+o move_index +1    #i ▶ #         next
hc keybind Super+Escape reload            #i ◙ # Reload config

#i ⮧ ←→↑↓

dir=("left" "right" "up" "down")
key=("h" "l" "k" "j")
for i in 0 1 2 3; do
  hc keybind Super+${key[$i]} focus ${dir[$i]}
  hc keybind Super+Shift+${key[$i]} shift ${dir[$i]}
  hc keybind Super+Mod1+${key[$i]} resize ${dir[$i]} +0.05
done

# Mouse
hc mouseunbind
hc mousebind Super+B1 move
hc mousebind Super+B3 resize
hc mousebind Super+B2 zoom

# Tags
hc rename default 1
hc keybind Super+1 use 1
hc keybind Super+Shift+1 move 1
for i in `seq 2 4`; do
  hc add $i
  hc keybind Super+$i use $i
  hc keybind Super+Shift+$i move $i
done

# Programs
hc keybind Super+Return spawn ~/scripts/dmenu_fav

# Rules
hc unrule --all
hc rule title=stalonetray manage=off
hc rule class=Conky manage=off
hc rule windowtype=_NET_WM_WINDOW_TYPE_DIALOG focus=on manage=off

# Go go go
herbstclient chain $cmds &

