#!/usr/bin/bash

## COLORS
cb='#121317'
cf='#a5a9b5'
c0='#1e2d33'
c1='#802828'
c2='#909737'
c3='#b27d12'
c4='#1e5673'
c5='#642337'
c6='#196271'
c7='#99b3bd'
c9='#334d57'
c8='#8a3232'
cr='^bg()^fg()'

## FONT
fn="lemon:size=10"

## RESOLUTION
xr="`xrandr | awk '/*+/ {print $1}'`"
res="${xr%x*}"
gap="${1:-8}"

sep="^fg($c0)·^fg()" 
asep="^fg($c0)⮁^fg()" 

batt() {
  if [[ -z "`ls /sys/class/power_supply/BAT*`" ]]; then
    echo "^fg($c0)⮎^fg()"
    return
  fi

  cf="`cat /sys/class/power_supply/BAT*/{energy,charge}_full 2>/dev/null`" 
  cn="`cat /sys/class/power_supply/BAT*/{energy,charge}_now 2>/dev/null`" 
  cs="`cat /sys/class/power_supply/BAT*/status`" 
  cp="`echo $cf $cn | awk '{print int($2/$1 * 100.0)}'`"

  ico="^fg($cf)⮏^fg() ${cp}%"
  [[ $cp -lt 20 ]]        && ico="^fg($c1)⮑ ${cp}%^fg()"
  [[ $cs == "Charging" ]] && ico="^fg($cf)⮒ ${cp}%^fg()"
  [[ $cs == "Full" ]]     && ico="^fg($cf)⮎^fg()"

  echo "$ico"
}

wifi() {
  lq="`awk '/wl/ {print int($3)}' /proc/net/wireless`"
  id="`connmanctl services | awk '/^*/ {print $2}'`"
  echo $id $lq
}

eth() {
  link="`ip link | awk '/: e/ && /UP/ {sub(/:/,\"\",$2);print $2}'`"
  cat /sys/class/net/$link/operstate
}

net() {
  if [[ `eth` == "up" ]]; then
    echo "^fg($c2)⮷^fg() eth"
    return
  fi
  wi=( `wifi` )
  [[ -z ${wi[1]} ]] && ico="^fg($c1)⮹^fg()" || ico="^fg($c4)⮷ ${wi[1]}^fg()"  
  if [[ -n ${wi[0]} ]]; then
    echo "$ico ${wi[0]}"
  else
    echo "^fg($c0)⮹ disconnected^fg()"
  fi
}


day() {
  date +"%a %d %b  ^fg($c4)%H:%M"
}

tags() {
  t="`herbstclient tag_status`"
  t="${t//\#/${cr}^fg($c4)}"
  t="${t//:/${cr}}"
  t="${t//./${cr}^fg($c0)}"
  t="${t//!/${cr}^fg($c1)}${cr}"
  echo $t
}

focus() {
  herbstclient get_attr clients.focus.title
}

herbstclient --wait reload &
wpid=$!
while kill -0 $wpid >/dev/null 2>&1; do
   left=" `tags` $asep  "
  right="`net`  $sep  `batt`  $sep  `day` "
  clean="`echo ${right} | sed -e "s/\^[fb]g([\#a-f0-9]*)//g"`"
     tw=`xftwidth $fn "${clean}   "`

     echo -e "${left}^p(_RIGHT)^p(-$tw)${right}"
  sleep 0.5s
done | dzen2 \
  -w $(( $res - 2 * $gap )) -h 16 -x $gap -y $gap \
  -bg $cb -fg $cf \
  -ta l
