#!/usr/bin/bash

hc() {
  herbstclient "$@"
}

ns() {
  #notify-send "$@"
  dunstify "$@"
}

vol_change() {
  chars=50
  sh-volctl $1
  amixer sget Master,0 | awk '
  /^  Front Left/ {
    sub(/\[/,"",$5); 
    sub(/%\]/,"",$5);
    lvl=int( $5/100.0 * nch );
  }
  END {
    i=0;
    for (;i<lvl;i++) {printf "■"};
    for (;i<nch;i++) {printf " "};
    print "";
  }' nch=$chars 
}

herbd_start() {
  hlwm_id=101
  vol_id=102

  # -- keybinds
  hc keybind Super+t emit_hook show_time
  hc keybind Super+r emit_hook show_battery
  hc keybind Super+9 emit_hook vol_down
  hc keybind Super+0 emit_hook vol_up
  hc keybind Super+8 emit_hook vol_mute
  # -- /keybinds

  # -- monitor daemons
  herbstclient --wait kill_herbd &
  wait_pid=$!
  while kill -0 $wait_pid >/dev/null 2>&1
  do
    info=( `acpi -b` )
    perc=${info[3]%%%*}
    [[ $perc -lt 15 ]] && ns -u critical -a acpi '⮐' "<b>Battery low!</b> (${perc}%)"
    sleep 1m
  done & 
  while kill -0 $wait_pid >/dev/null 2>&1
  do
    upd=`checkupdates | wc -l`
    [[ $upd -gt 0 ]] && ns -u critical -a pacman '⮢' "$upd updates available"
    sleep 1h
  done & 
  # -- /monitor daemons

  # -- notify daemon
  hc --idle | (
    while read line; do
      cmds=($line)
      case ${cmds[0]} in

        "show_time")
          ns -u normal -t 1 -a hlwm -r $hlwm_id '⮖' "`date`"
          ;;
        
        "show_battery")
          ns -u normal -t 1 -a hlwm -r $hlwm_id '⮏' "`acpi --battery`"
          ;;
        
        "tag_changed")
          #ns -u low -t 1 -a hlwm -r $hlwm_id '⮧' "t: ${cmds[1]}  m: ${cmds[2]}"
          ;;

        "focus_changed")
          title="${cmds[@]:2}"
          ns -u low -t 1 -a hlwm -r $hlwm_id '⮛' "$title" 
          ;;

        "urgent")
          [[ ${cmds[1]} == "on" ]] && ns -u critical -a hlwm -r $hlwm_id '<b>!</b>' "`herbstclient attr clients.${cmds[2]}.title`"
          ;;

        "vol_up")
          ns -u normal -t 1 -a vol -r $vol_id '⮟' "`vol_change up`"
          ;;

        "vol_down")
          ns -u normal -t 1 -a vol -r $vol_id '⮟' "`vol_change down`"
          ;;

        "vol_mute")
          sh-volctl mute
          ns -u normal -t 1 -a vol -r $vol_id '⮝' "-- MUTE --"
          ;;

        "kill_herbd")
          break
          ;;

        *)
          continue
          ;;

      esac
    done
    killall herbstclient
    ) &
  # -- /notify daemon
}

herbd_stop() {
  hc emit_hook kill_herbd
}

herbd_restart() {
  herbd_stop
  herbd_start
}
