#!/bin/bash

## ALIASES

[[ -e /usr/bin/yaourt ]] && pacman="yaourt" || pacman="sudo pacman"

# Shell commands
alias ls='echo; ls --group-directories-first --color=always --classify -h'
alias cp='cp -i'
alias mv='mv -i'
alias rmrf='rm -rfI'
alias df='echo; df -h'
alias du='echo; du -h'
alias dud='echo; du -hcs * | sort -hr'
alias la='echo; ls -lA'
alias grep='grep --color=auto'
alias dmesg='dmesg --color'
alias s='ssh'
alias ocd='cd -'

# Actions
alias redot='source $HOME/.bashrc'
alias rex='xrdb -merge $XDG_CONFIG_HOME/xorg/xresources'
alias lastj="sudo journalctl --since=today | tac | sed -n '/-- Reboot --/{n;:r;/-- Reboot --/q;p;n;b r}' | tac"
alias xloc="DISPLAY=:0"
alias po="sudo poweroff"
alias re="sudo reboot"

# Launchers
alias valgr='valgrind --db-attach=yes --leak-check=yes --tool=memcheck --num-callers=16 --leak-resolution=high --track-origins=yes'
alias clock='tty-clock -c -C4 -f"%a %d %b, %Y"'
alias o='xdg-open'

# Force stuff to obey XDG
alias tmux='tmux -f $XDG_CONFIG_HOME/tmux/tmux.conf'
alias irssi='irssi --home=$XDG_CONFIG_HOME/irssi'
alias rtorrent="rtorrent -n -o import=${XDG_CONFIG_HOME}/rtorrent/config.rc"
alias weechat="weechat -d $XDG_CONFIG_HOME/weechat"
alias skype="skype --dbpath=$XDG_CONFIG_HOME/skype"
alias easystroke="easystroke -c $XDG_CONFIG_HOME/easystroke"
alias mypaint="mypaint -c $XDG_CONFIG_HOME/mypaint"

# Pacman
alias Pins="$pacman -S"
alias Punins='sudo pacman -Rnssc'
alias Pinfo="$pacman -Qi"
alias Pgetinfo="$pacman -Si"
alias Pown="$pacman -Qo"
alias Pstat="$pacman -Qs"
alias Pfiles="$pacman -Ql"
alias Pfind="yaourt"
alias Ppupd="sudo pacman -Syyu"
alias Paupd="yaourt -Syua"
alias Plist="$pacman -Qqe"
alias Palist="$pacman -Qqm"

# Herbstluftwm
alias jj="$XDG_CONFIG_HOME/herbstluftwm/jump j"
alias jb="$XDG_CONFIG_HOME/herbstluftwm/jump b"

# Clipboard
alias Cpr="xclip -o -selection PRIMARY"
alias Cse="xclip -o -selection SECONDARY"
alias Ccl="xclip -o -selection CLIPBOARD"
alias Cc="xclip -i -selection PRIMARY"

## FUNCTIONS

# Pastebin
ix() {
  curl -n -F 'f:1=<-' http://ix.io | xclip -i -selection PRIMARY
}

astart() {
  [[ -z `pidof $1` ]] && $@
}

cstart() {
  while [[ -z `pidof $1` ]]; do
    sleep .5
  done
  astart ${@:2}
}

man() {
    env LESS_TERMCAP_mb=$'\E[01;31m' \
    LESS_TERMCAP_md=$'\E[01;38;5;74m' \
    LESS_TERMCAP_me=$'\E[0m' \
    LESS_TERMCAP_se=$'\E[0m' \
    LESS_TERMCAP_so=$'\E[38;5;246m' \
    LESS_TERMCAP_ue=$'\E[0m' \
    LESS_TERMCAP_us=$'\E[04;38;5;146m' \
    man "$@"
}

lns() {
  ln -s `realpath $1` $2
}

mpvp() {
  if [[ $1 == "tv" ]]; then
    url="${2:-`xclip -o -selection clipboard`}"
    herbstclient reload
    args="--no-cache --ao=alsa:device=hdmi --title=playontv $url"
  else
    args="${1:-`xclip -o -selection clipboard`}"
  fi
  mpv $args
} 

