#!/bin/bash

# Set custom history file
HISTFILE=$HOME/.bashrun_history
HISTCONTROL=ignoredups:erasedups

# Set prompt
PS1="\[\e[;33m\] \[\e[m\]"

# bind <TAB> to menu-complete. Makes <TAB> cycle through completions on
# the current line instead of paging all possible completions
bind '"\t": menu-complete'

# bind <Enter> to add ' &' to command line
# set -t closes the instance
bind '"\x0d"':"\" &\nset -t\n\""

