"         o             
"   _  _  _   
"   |  |_|  / |/ |/ |  
"    \/  |_/  |  |  |_/
"  


set nocompatible


" -- Environment
set directory=$XDG_CACHE_HOME/vim,~/,/tmp
set backupdir=$XDG_CACHE_HOME/vim,~/,/tmp
set viminfo+=n$XDG_CACHE_HOME/vim/viminfo
set runtimepath=$XDG_CONFIG_HOME/vim,$XDG_CONFIG_HOME/vim/after,$VIM,$VIMRUNTIME
let $MYVIMRC="$XDG_CONFIG_HOME/vim/vimrc"
" -- /Environment
"

" -- vundle
filetype off
set rtp+=$XDG_CONFIG_HOME/vim/bundle/Vundle.vim
call vundle#begin()
Plugin 'gmarik/Vundle.vim'
Plugin 'szw/vim-tags'
Plugin 'tpope/vim-surround'
Plugin 'ervandew/supertab'
call vundle#end()
" -- /vundle


" -- colours
syntax on
let base16colorspace=256
set background=dark
colorscheme base16-default
" -- /colours


" -- latex
function WrapOn()
  setlocal cc=-1
  setlocal textwidth=0
  setlocal wrap linebreak nolist
  setlocal display+=lastline
  setlocal whichwrap+=<,>,[,]
  setlocal foldlevel=10
  let &showbreak="| "
  noremap  <buffer> <silent> <Up>   gk
  noremap  <buffer> <silent> <Down> gj
  noremap  <buffer> <silent> <Home> g<Home>
  noremap  <buffer> <silent> <End>  g<End>
  inoremap <buffer> <silent> <Up>   <C-o>gk
  inoremap <buffer> <silent> <Down> <C-o>gj
  inoremap <buffer> <silent> <Home> <C-o>g<Home>
  inoremap <buffer> <silent> <End>  <C-o>g<End>
endfunction
let g:tex_flavor='latex'
" -- /latex


" -- filetype specific
au BufNewFile,BufRead *.tex call WrapOn()
au BufNewFile,BufRead *.src set filetype=fortran
au BufNewFile,BufRead *.fcm set filetype=fortran
au BufNewFile,BufRead *.frag,*.vert,*.fp,*.vp,*.glsl set filetype=glsl
" -- /filetype specific


" -- general
filetype plugin indent on
set incsearch
set scrolloff=2
set ignorecase
set smartcase
set expandtab
set tabstop=2
set shiftwidth=2
set laststatus=2
set nowrap
set number
set modeline
set clipboard+=unnamed
set backspace+=start,eol,indent
set omnifunc=syntaxcomplete#Complete
" -- /general


" -- plugins
let g:SuperTabDefaultCompletionType = "context"
" -- /plugins


" -- bindings
map <F3> :w !detex \| wc -w <CR>
map <silent> <F4> :set wrap! linebreak! nolist! <CR> 
" -- /bindings

