#!/bin/bash
#
# Autostart file for host vix60

# Set correct gamma
xgamma -gamma 1.25 &

# Tablet buttons for pekwm menus
(sudo setkeycodes 68 122 6c 135 6b 136 6e 140 6d 141 71 142 6f 143 &&
 xmodmap ~/.config/`hostname`/xmodmap) &

# rxvt-unicode daemon
urxvtd -q -f -o &

# pcmanfm daemon
pcmanfm -d &

# set wallpaper with feh
feh --bg-center ~/img/wall/busstop.jpg

# tint2 taskbar
tint2 &

# Copy (qt app) for syncing
~/apps/copy/x86/CopyAgent &

