#!/bin/bash

# Shell commands
alias ls='ls --group-directories-first --color=always --classify -h'
alias less='less -RS'
alias cp='cp -i'
alias mv='mv -i'
alias rmr='rm -rfI'
alias df='df -h'
alias du='du -h'
alias dud='du -hcs .[!.]* * | sort -hr'
alias la='ls -lA'
alias grep='grep --color=auto'
alias dmesg='dmesg --color'
alias ocd='cd -'

# Shorten stuff
alias s='ssh'
alias l='ls'
alias t="tmux -f $XDG_CONFIG_HOME/tmux/local.conf"
alias g='grep --color=always -Rni'
alias e="$EDITOR"
alias q='exit'
alias ry='rsync -ahv --progress --stats'
alias za='zathura --fork'

# Actions
alias po="sudo poweroff"
alias re="sudo reboot"

# Utils
alias redot="source $SHELL_CONFIG"
alias rexrdb='xrdb -merge $XDG_CONFIG_HOME/xorg/xresources'
alias lastj="sudo journalctl -b-1"
alias valgr='valgrind --db-attach=yes --leak-check=yes --tool=memcheck --num-callers=16 --leak-resolution=high --track-origins=yes'

# Force stuff to obey XDG
alias weechat="weechat -d $XDG_CONFIG_HOME/weechat"
alias skype="skype --dbpath=$XDG_CONFIG_HOME/skype"
alias easystroke="easystroke -c $XDG_CONFIG_HOME/easystroke"
alias mypaint="mypaint -c $XDG_CONFIG_HOME/mypaint"

# Clipboard
alias Cpr="xclip -o -selection PRIMARY"
alias Cse="xclip -o -selection SECONDARY"
alias Ccl="xclip -o -selection CLIPBOARD"
alias Cc="xclip -i -selection PRIMARY"

# Virtualenv
alias ve="virtualenv virt"
alias va="source virt/bin/activate"
alias vd="deactivate"

# Neovim
alias vim="nvim"
